// Code generated by protoc-gen-validation. DO NOT EDIT.

package kubeproto

import (
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"reflect"
	"regexp"
	"strconv"
	"strings"

	"github.com/google/uuid"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = reflect.ValueOf
var _ = regexp.MatchString
var _ = uuid.Parse
var _ = mail.ParseAddress
var _ = strings.Contains
var _ = net.ParseIP
var _ = mail.ParseAddress
var _ = url.ParseRequestURI
var _ = codes.InvalidArgument
var _ = status.Error
var _ = strconv.Itoa

// sampleMessageValidateExt is an extension hook for additional validation logic
var sampleMessageValidateExt func(*SampleMessage, string) error

func (this *SampleMessage) Validate(prefix string) error {

	{
		v := this.GetRelation_4()
		n := `relation_4`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if sampleMessageValidateExt != nil {
		if err := sampleMessageValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterSampleMessageValidateExt registers an extension validation function
func RegisterSampleMessageValidateExt(f func(*SampleMessage, string) error) {
	sampleMessageValidateExt = f
}

// testIndexingSpecValidateExt is an extension hook for additional validation logic
var testIndexingSpecValidateExt func(*TestIndexingSpec, string) error

func (this *TestIndexingSpec) Validate(prefix string) error {

	{
		v := this.GetSampleMsg()
		n := `sample_msg`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetIndexedResourceId()
		n := `indexed_resource_id`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetIndexedUserInfo()
		n := `indexed_user_info`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	if f, ok := this.OneOfField.(*TestIndexingSpec_OneOfSampleMsg); ok {
		v := f.OneOfSampleMsg
		n := `one_of_sample_msg`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if testIndexingSpecValidateExt != nil {
		if err := testIndexingSpecValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestIndexingSpecValidateExt registers an extension validation function
func RegisterTestIndexingSpecValidateExt(f func(*TestIndexingSpec, string) error) {
	testIndexingSpecValidateExt = f
}

// testIndexingStatusValidateExt is an extension hook for additional validation logic
var testIndexingStatusValidateExt func(*TestIndexingStatus, string) error

func (this *TestIndexingStatus) Validate(prefix string) error {

	{
		v := this.GetTimeMsg()
		n := `time_msg`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if testIndexingStatusValidateExt != nil {
		if err := testIndexingStatusValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestIndexingStatusValidateExt registers an extension validation function
func RegisterTestIndexingStatusValidateExt(f func(*TestIndexingStatus, string) error) {
	testIndexingStatusValidateExt = f
}

// testIndexingValidateExt is an extension hook for additional validation logic
var testIndexingValidateExt func(*TestIndexing, string) error

func (this *TestIndexing) Validate(prefix string) error {

	{
		v := this.GetTypeMeta()
		n := `type_meta`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetMetadata()
		n := `metadata`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetSpec()
		n := `spec`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetStatus()
		n := `status`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if testIndexingValidateExt != nil {
		if err := testIndexingValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestIndexingValidateExt registers an extension validation function
func RegisterTestIndexingValidateExt(f func(*TestIndexing, string) error) {
	testIndexingValidateExt = f
}

// testIndexingListValidateExt is an extension hook for additional validation logic
var testIndexingListValidateExt func(*TestIndexingList, string) error

func (this *TestIndexingList) Validate(prefix string) error {

	{
		v := this.GetTypeMeta()
		n := `type_meta`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetMetadata()
		n := `metadata`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetItems()
		for i, v := range v {
			n := `items[` + strconv.Itoa(i) + `]`

			var i interface{}
			if reflect.ValueOf(v).Kind() == reflect.Ptr {
				i = reflect.ValueOf(v).Interface()
				if reflect.ValueOf(v).IsNil() {
					i = nil
				}
			} else {
				i = reflect.ValueOf(&v).Interface()
			}
			validate, hasValidate := i.(interface{ Validate(string) error })
			if hasValidate {
				if err := validate.Validate(prefix + n + "."); err != nil {
					return err
				}
			}
		}
	}
	// Call extension validation if registered
	if testIndexingListValidateExt != nil {
		if err := testIndexingListValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestIndexingListValidateExt registers an extension validation function
func RegisterTestIndexingListValidateExt(f func(*TestIndexingList, string) error) {
	testIndexingListValidateExt = f
}

// testBaseSpecValidateExt is an extension hook for additional validation logic
var testBaseSpecValidateExt func(*TestBaseSpec, string) error

func (this *TestBaseSpec) Validate(prefix string) error {

	{
		v := this.GetRef()
		n := `ref`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if testBaseSpecValidateExt != nil {
		if err := testBaseSpecValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestBaseSpecValidateExt registers an extension validation function
func RegisterTestBaseSpecValidateExt(f func(*TestBaseSpec, string) error) {
	testBaseSpecValidateExt = f
}

// testBaseStatusValidateExt is an extension hook for additional validation logic
var testBaseStatusValidateExt func(*TestBaseStatus, string) error

func (this *TestBaseStatus) Validate(prefix string) error {

	// Call extension validation if registered
	if testBaseStatusValidateExt != nil {
		if err := testBaseStatusValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestBaseStatusValidateExt registers an extension validation function
func RegisterTestBaseStatusValidateExt(f func(*TestBaseStatus, string) error) {
	testBaseStatusValidateExt = f
}

// testBaseValidateExt is an extension hook for additional validation logic
var testBaseValidateExt func(*TestBase, string) error

func (this *TestBase) Validate(prefix string) error {

	{
		v := this.GetTypeMeta()
		n := `type_meta`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetMetadata()
		n := `metadata`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetSpec()
		n := `spec`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetStatus()
		n := `status`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if testBaseValidateExt != nil {
		if err := testBaseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestBaseValidateExt registers an extension validation function
func RegisterTestBaseValidateExt(f func(*TestBase, string) error) {
	testBaseValidateExt = f
}

// testBaseListValidateExt is an extension hook for additional validation logic
var testBaseListValidateExt func(*TestBaseList, string) error

func (this *TestBaseList) Validate(prefix string) error {

	{
		v := this.GetTypeMeta()
		n := `type_meta`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetMetadata()
		n := `metadata`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetItems()
		for i, v := range v {
			n := `items[` + strconv.Itoa(i) + `]`

			var i interface{}
			if reflect.ValueOf(v).Kind() == reflect.Ptr {
				i = reflect.ValueOf(v).Interface()
				if reflect.ValueOf(v).IsNil() {
					i = nil
				}
			} else {
				i = reflect.ValueOf(&v).Interface()
			}
			validate, hasValidate := i.(interface{ Validate(string) error })
			if hasValidate {
				if err := validate.Validate(prefix + n + "."); err != nil {
					return err
				}
			}
		}
	}
	// Call extension validation if registered
	if testBaseListValidateExt != nil {
		if err := testBaseListValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestBaseListValidateExt registers an extension validation function
func RegisterTestBaseListValidateExt(f func(*TestBaseList, string) error) {
	testBaseListValidateExt = f
}

// testWrapperSpecValidateExt is an extension hook for additional validation logic
var testWrapperSpecValidateExt func(*TestWrapperSpec, string) error

func (this *TestWrapperSpec) Validate(prefix string) error {

	// Call extension validation if registered
	if testWrapperSpecValidateExt != nil {
		if err := testWrapperSpecValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestWrapperSpecValidateExt registers an extension validation function
func RegisterTestWrapperSpecValidateExt(f func(*TestWrapperSpec, string) error) {
	testWrapperSpecValidateExt = f
}

// testWrapperStatusValidateExt is an extension hook for additional validation logic
var testWrapperStatusValidateExt func(*TestWrapperStatus, string) error

func (this *TestWrapperStatus) Validate(prefix string) error {

	// Call extension validation if registered
	if testWrapperStatusValidateExt != nil {
		if err := testWrapperStatusValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestWrapperStatusValidateExt registers an extension validation function
func RegisterTestWrapperStatusValidateExt(f func(*TestWrapperStatus, string) error) {
	testWrapperStatusValidateExt = f
}

// testWrapperValidateExt is an extension hook for additional validation logic
var testWrapperValidateExt func(*TestWrapper, string) error

func (this *TestWrapper) Validate(prefix string) error {

	{
		v := this.GetTypeMeta()
		n := `type_meta`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetMetadata()
		n := `metadata`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetSpec()
		n := `spec`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetStatus()
		n := `status`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if testWrapperValidateExt != nil {
		if err := testWrapperValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestWrapperValidateExt registers an extension validation function
func RegisterTestWrapperValidateExt(f func(*TestWrapper, string) error) {
	testWrapperValidateExt = f
}

// testWrapperListValidateExt is an extension hook for additional validation logic
var testWrapperListValidateExt func(*TestWrapperList, string) error

func (this *TestWrapperList) Validate(prefix string) error {

	{
		v := this.GetTypeMeta()
		n := `type_meta`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetMetadata()
		n := `metadata`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetItems()
		for i, v := range v {
			n := `items[` + strconv.Itoa(i) + `]`

			var i interface{}
			if reflect.ValueOf(v).Kind() == reflect.Ptr {
				i = reflect.ValueOf(v).Interface()
				if reflect.ValueOf(v).IsNil() {
					i = nil
				}
			} else {
				i = reflect.ValueOf(&v).Interface()
			}
			validate, hasValidate := i.(interface{ Validate(string) error })
			if hasValidate {
				if err := validate.Validate(prefix + n + "."); err != nil {
					return err
				}
			}
		}
	}
	// Call extension validation if registered
	if testWrapperListValidateExt != nil {
		if err := testWrapperListValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestWrapperListValidateExt registers an extension validation function
func RegisterTestWrapperListValidateExt(f func(*TestWrapperList, string) error) {
	testWrapperListValidateExt = f
}

// testDraftSpecValidateExt is an extension hook for additional validation logic
var testDraftSpecValidateExt func(*TestDraftSpec, string) error

func (this *TestDraftSpec) Validate(prefix string) error {

	// Call extension validation if registered
	if testDraftSpecValidateExt != nil {
		if err := testDraftSpecValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestDraftSpecValidateExt registers an extension validation function
func RegisterTestDraftSpecValidateExt(f func(*TestDraftSpec, string) error) {
	testDraftSpecValidateExt = f
}

// testDraftStatusValidateExt is an extension hook for additional validation logic
var testDraftStatusValidateExt func(*TestDraftStatus, string) error

func (this *TestDraftStatus) Validate(prefix string) error {

	// Call extension validation if registered
	if testDraftStatusValidateExt != nil {
		if err := testDraftStatusValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestDraftStatusValidateExt registers an extension validation function
func RegisterTestDraftStatusValidateExt(f func(*TestDraftStatus, string) error) {
	testDraftStatusValidateExt = f
}

// testDraftValidateExt is an extension hook for additional validation logic
var testDraftValidateExt func(*TestDraft, string) error

func (this *TestDraft) Validate(prefix string) error {

	{
		v := this.GetTypeMeta()
		n := `type_meta`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetMetadata()
		n := `metadata`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetSpec()
		n := `spec`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetStatus()
		n := `status`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if testDraftValidateExt != nil {
		if err := testDraftValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestDraftValidateExt registers an extension validation function
func RegisterTestDraftValidateExt(f func(*TestDraft, string) error) {
	testDraftValidateExt = f
}

// testDraftListValidateExt is an extension hook for additional validation logic
var testDraftListValidateExt func(*TestDraftList, string) error

func (this *TestDraftList) Validate(prefix string) error {

	{
		v := this.GetTypeMeta()
		n := `type_meta`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetMetadata()
		n := `metadata`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetItems()
		for i, v := range v {
			n := `items[` + strconv.Itoa(i) + `]`

			var i interface{}
			if reflect.ValueOf(v).Kind() == reflect.Ptr {
				i = reflect.ValueOf(v).Interface()
				if reflect.ValueOf(v).IsNil() {
					i = nil
				}
			} else {
				i = reflect.ValueOf(&v).Interface()
			}
			validate, hasValidate := i.(interface{ Validate(string) error })
			if hasValidate {
				if err := validate.Validate(prefix + n + "."); err != nil {
					return err
				}
			}
		}
	}
	// Call extension validation if registered
	if testDraftListValidateExt != nil {
		if err := testDraftListValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTestDraftListValidateExt registers an extension validation function
func RegisterTestDraftListValidateExt(f func(*TestDraftList, string) error) {
	testDraftListValidateExt = f
}
