// Code generated by protoc-gen-validation. DO NOT EDIT.

package kubeproto

import (
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"reflect"
	"regexp"
	"strconv"
	"strings"

	"github.com/google/uuid"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = reflect.ValueOf
var _ = regexp.MatchString
var _ = uuid.Parse
var _ = mail.ParseAddress
var _ = strings.Contains
var _ = net.ParseIP
var _ = mail.ParseAddress
var _ = url.ParseRequestURI
var _ = codes.InvalidArgument
var _ = status.Error
var _ = strconv.Itoa

// int64JsonNestedValidateExt is an extension hook for additional validation logic
var int64JsonNestedValidateExt func(*Int64JsonNested, string) error

func (this *Int64JsonNested) Validate(prefix string) error {

	// Call extension validation if registered
	if int64JsonNestedValidateExt != nil {
		if err := int64JsonNestedValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterInt64JsonNestedValidateExt registers an extension validation function
func RegisterInt64JsonNestedValidateExt(f func(*Int64JsonNested, string) error) {
	int64JsonNestedValidateExt = f
}

// int64JsonConditionValidateExt is an extension hook for additional validation logic
var int64JsonConditionValidateExt func(*Int64JsonCondition, string) error

func (this *Int64JsonCondition) Validate(prefix string) error {

	// Call extension validation if registered
	if int64JsonConditionValidateExt != nil {
		if err := int64JsonConditionValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterInt64JsonConditionValidateExt registers an extension validation function
func RegisterInt64JsonConditionValidateExt(f func(*Int64JsonCondition, string) error) {
	int64JsonConditionValidateExt = f
}

// int64JsonFixtureSpecValidateExt is an extension hook for additional validation logic
var int64JsonFixtureSpecValidateExt func(*Int64JsonFixtureSpec, string) error

func (this *Int64JsonFixtureSpec) Validate(prefix string) error {

	{
		v := this.GetNested()
		n := `nested`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if int64JsonFixtureSpecValidateExt != nil {
		if err := int64JsonFixtureSpecValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterInt64JsonFixtureSpecValidateExt registers an extension validation function
func RegisterInt64JsonFixtureSpecValidateExt(f func(*Int64JsonFixtureSpec, string) error) {
	int64JsonFixtureSpecValidateExt = f
}

// int64JsonFixtureStatusValidateExt is an extension hook for additional validation logic
var int64JsonFixtureStatusValidateExt func(*Int64JsonFixtureStatus, string) error

func (this *Int64JsonFixtureStatus) Validate(prefix string) error {

	{
		v := this.GetConditions()
		for i, v := range v {
			n := `conditions[` + strconv.Itoa(i) + `]`

			var i interface{}
			if reflect.ValueOf(v).Kind() == reflect.Ptr {
				i = reflect.ValueOf(v).Interface()
				if reflect.ValueOf(v).IsNil() {
					i = nil
				}
			} else {
				i = reflect.ValueOf(&v).Interface()
			}
			validate, hasValidate := i.(interface{ Validate(string) error })
			if hasValidate {
				if err := validate.Validate(prefix + n + "."); err != nil {
					return err
				}
			}
		}
	}
	// Call extension validation if registered
	if int64JsonFixtureStatusValidateExt != nil {
		if err := int64JsonFixtureStatusValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterInt64JsonFixtureStatusValidateExt registers an extension validation function
func RegisterInt64JsonFixtureStatusValidateExt(f func(*Int64JsonFixtureStatus, string) error) {
	int64JsonFixtureStatusValidateExt = f
}

// int64JsonFixtureValidateExt is an extension hook for additional validation logic
var int64JsonFixtureValidateExt func(*Int64JsonFixture, string) error

func (this *Int64JsonFixture) Validate(prefix string) error {

	{
		v := this.GetTypeMeta()
		n := `type_meta`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetMetadata()
		n := `metadata`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetSpec()
		n := `spec`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetStatus()
		n := `status`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if int64JsonFixtureValidateExt != nil {
		if err := int64JsonFixtureValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterInt64JsonFixtureValidateExt registers an extension validation function
func RegisterInt64JsonFixtureValidateExt(f func(*Int64JsonFixture, string) error) {
	int64JsonFixtureValidateExt = f
}

// updateInt64JsonFixtureRequestValidateExt is an extension hook for additional validation logic
var updateInt64JsonFixtureRequestValidateExt func(*UpdateInt64JsonFixtureRequest, string) error

func (this *UpdateInt64JsonFixtureRequest) Validate(prefix string) error {

	{
		v := this.GetFixture()
		n := `fixture`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if updateInt64JsonFixtureRequestValidateExt != nil {
		if err := updateInt64JsonFixtureRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterUpdateInt64JsonFixtureRequestValidateExt registers an extension validation function
func RegisterUpdateInt64JsonFixtureRequestValidateExt(f func(*UpdateInt64JsonFixtureRequest, string) error) {
	updateInt64JsonFixtureRequestValidateExt = f
}
