// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: michelangelo/test/kubeproto/int64_json_ut.proto

package kubeproto

import (
	"bytes"
	"encoding/json"
	"github.com/gogo/protobuf/jsonpb"
	"github.com/michelangelo-ai/michelangelo/go/kubeproto/util"
	"github.com/michelangelo-ai/michelangelo/go/storage"
	k8sruntime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"

	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/michelangelo-ai/michelangelo/proto-go/api"
	io "io"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Int64JsonNested struct {
	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Total int64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (m *Int64JsonNested) Reset()      { *m = Int64JsonNested{} }
func (*Int64JsonNested) ProtoMessage() {}
func (*Int64JsonNested) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ff5147d6f5bee3, []int{0}
}
func (m *Int64JsonNested) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Int64JsonNested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Int64JsonNested.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Int64JsonNested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64JsonNested.Merge(m, src)
}
func (m *Int64JsonNested) XXX_Size() int {
	return m.Size()
}
func (m *Int64JsonNested) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64JsonNested.DiscardUnknown(m)
}

var xxx_messageInfo_Int64JsonNested proto.InternalMessageInfo

func (m *Int64JsonNested) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Int64JsonNested) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Int64JsonCondition struct {
	ObservedGeneration int64 `protobuf:"varint,1,opt,name=observed_generation,json=observedGeneration,proto3" json:"observedGeneration,omitempty"`
}

func (m *Int64JsonCondition) Reset()      { *m = Int64JsonCondition{} }
func (*Int64JsonCondition) ProtoMessage() {}
func (*Int64JsonCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ff5147d6f5bee3, []int{1}
}
func (m *Int64JsonCondition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Int64JsonCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Int64JsonCondition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Int64JsonCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64JsonCondition.Merge(m, src)
}
func (m *Int64JsonCondition) XXX_Size() int {
	return m.Size()
}
func (m *Int64JsonCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64JsonCondition.DiscardUnknown(m)
}

var xxx_messageInfo_Int64JsonCondition proto.InternalMessageInfo

func (m *Int64JsonCondition) GetObservedGeneration() int64 {
	if m != nil {
		return m.ObservedGeneration
	}
	return 0
}

type Int64JsonFixtureSpec struct {
	Nested *Int64JsonNested `protobuf:"bytes,1,opt,name=nested,proto3" json:"nested,omitempty"`
}

func (m *Int64JsonFixtureSpec) Reset()      { *m = Int64JsonFixtureSpec{} }
func (*Int64JsonFixtureSpec) ProtoMessage() {}
func (*Int64JsonFixtureSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ff5147d6f5bee3, []int{2}
}
func (m *Int64JsonFixtureSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Int64JsonFixtureSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Int64JsonFixtureSpec.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Int64JsonFixtureSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64JsonFixtureSpec.Merge(m, src)
}
func (m *Int64JsonFixtureSpec) XXX_Size() int {
	return m.Size()
}
func (m *Int64JsonFixtureSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64JsonFixtureSpec.DiscardUnknown(m)
}

var xxx_messageInfo_Int64JsonFixtureSpec proto.InternalMessageInfo

func (m *Int64JsonFixtureSpec) GetNested() *Int64JsonNested {
	if m != nil {
		return m.Nested
	}
	return nil
}

type Int64JsonFixtureStatus struct {
	ObservedGeneration int64                 `protobuf:"varint,1,opt,name=observed_generation,json=observedGeneration,proto3" json:"observedGeneration,omitempty"`
	Total              int64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Conditions         []*Int64JsonCondition `protobuf:"bytes,3,rep,name=conditions,proto3" json:"conditions,omitempty"`
}

func (m *Int64JsonFixtureStatus) Reset()      { *m = Int64JsonFixtureStatus{} }
func (*Int64JsonFixtureStatus) ProtoMessage() {}
func (*Int64JsonFixtureStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ff5147d6f5bee3, []int{3}
}
func (m *Int64JsonFixtureStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Int64JsonFixtureStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Int64JsonFixtureStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Int64JsonFixtureStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64JsonFixtureStatus.Merge(m, src)
}
func (m *Int64JsonFixtureStatus) XXX_Size() int {
	return m.Size()
}
func (m *Int64JsonFixtureStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64JsonFixtureStatus.DiscardUnknown(m)
}

var xxx_messageInfo_Int64JsonFixtureStatus proto.InternalMessageInfo

func (m *Int64JsonFixtureStatus) GetObservedGeneration() int64 {
	if m != nil {
		return m.ObservedGeneration
	}
	return 0
}

func (m *Int64JsonFixtureStatus) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Int64JsonFixtureStatus) GetConditions() []*Int64JsonCondition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *Int64JsonFixture) Reset()      { *m = Int64JsonFixture{} }
func (*Int64JsonFixture) ProtoMessage() {}
func (*Int64JsonFixture) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ff5147d6f5bee3, []int{4}
}
func (m *Int64JsonFixture) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Int64JsonFixture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Int64JsonFixture.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Int64JsonFixture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64JsonFixture.Merge(m, src)
}
func (m *Int64JsonFixture) XXX_Size() int {
	return m.Size()
}
func (m *Int64JsonFixture) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64JsonFixture.DiscardUnknown(m)
}

var xxx_messageInfo_Int64JsonFixture proto.InternalMessageInfo

type UpdateInt64JsonFixtureRequest struct {
	Fixture *Int64JsonFixture `protobuf:"bytes,1,opt,name=fixture,proto3" json:"fixture,omitempty"`
}

func (m *UpdateInt64JsonFixtureRequest) Reset()      { *m = UpdateInt64JsonFixtureRequest{} }
func (*UpdateInt64JsonFixtureRequest) ProtoMessage() {}
func (*UpdateInt64JsonFixtureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ff5147d6f5bee3, []int{5}
}
func (m *UpdateInt64JsonFixtureRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateInt64JsonFixtureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateInt64JsonFixtureRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdateInt64JsonFixtureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInt64JsonFixtureRequest.Merge(m, src)
}
func (m *UpdateInt64JsonFixtureRequest) XXX_Size() int {
	return m.Size()
}
func (m *UpdateInt64JsonFixtureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInt64JsonFixtureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInt64JsonFixtureRequest proto.InternalMessageInfo

func (m *UpdateInt64JsonFixtureRequest) GetFixture() *Int64JsonFixture {
	if m != nil {
		return m.Fixture
	}
	return nil
}

func init() {
	proto.RegisterType((*Int64JsonNested)(nil), "michelangelo.test.kubeproto.Int64JsonNested")
	proto.RegisterType((*Int64JsonCondition)(nil), "michelangelo.test.kubeproto.Int64JsonCondition")
	proto.RegisterType((*Int64JsonFixtureSpec)(nil), "michelangelo.test.kubeproto.Int64JsonFixtureSpec")
	proto.RegisterType((*Int64JsonFixtureStatus)(nil), "michelangelo.test.kubeproto.Int64JsonFixtureStatus")
	proto.RegisterType((*Int64JsonFixture)(nil), "michelangelo.test.kubeproto.Int64JsonFixture")
	proto.RegisterType((*UpdateInt64JsonFixtureRequest)(nil), "michelangelo.test.kubeproto.UpdateInt64JsonFixtureRequest")
}

func init() {
	proto.RegisterFile("michelangelo/test/kubeproto/int64_json_ut.proto", fileDescriptor_98ff5147d6f5bee3)
}

var fileDescriptor_98ff5147d6f5bee3 = []byte{
	// 522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x6e, 0xd3, 0x4e,
	0x10, 0xc6, 0xed, 0xa6, 0xff, 0xfe, 0xdb, 0x2d, 0x52, 0xd1, 0x52, 0xa1, 0xa8, 0x88, 0x55, 0xe5,
	0x53, 0x85, 0x60, 0x97, 0xa4, 0x15, 0x42, 0x20, 0x2e, 0x85, 0x52, 0x41, 0xa1, 0x95, 0x0c, 0x5c,
	0x10, 0x52, 0xb4, 0xb1, 0x87, 0xc4, 0x4d, 0xe2, 0x5d, 0xb2, 0xe3, 0x88, 0xdc, 0x10, 0x4f, 0xc0,
	0xa3, 0xf0, 0x18, 0x1c, 0x23, 0x4e, 0x3d, 0x12, 0xe7, 0xc2, 0xb1, 0x8f, 0x80, 0xbc, 0x76, 0xac,
	0x10, 0x10, 0x4a, 0x4e, 0xf6, 0x7e, 0xe3, 0xef, 0xe7, 0x6f, 0x66, 0x96, 0x88, 0x5e, 0x14, 0xb4,
	0xa1, 0x2b, 0xe3, 0x16, 0x74, 0x95, 0x40, 0x30, 0x28, 0x3a, 0x49, 0x13, 0x74, 0x5f, 0xa1, 0x12,
	0x51, 0x8c, 0xf7, 0x0e, 0x1a, 0xe7, 0x46, 0xc5, 0x8d, 0x04, 0xb9, 0xd5, 0xe8, 0x8d, 0x59, 0x03,
	0xcf, 0x0c, 0xbc, 0x34, 0xec, 0x1c, 0x74, 0xee, 0x1b, 0x1e, 0x29, 0x21, 0x75, 0xd4, 0x93, 0x41,
	0x3b, 0x8a, 0xa1, 0x3f, 0x14, 0xba, 0xd3, 0xca, 0x04, 0x23, 0x7a, 0x80, 0x52, 0x0c, 0x6a, 0xa2,
	0x05, 0x31, 0xf4, 0x25, 0x42, 0x98, 0x23, 0x77, 0xd8, 0x6f, 0x19, 0xa4, 0x8e, 0x84, 0xd2, 0x18,
	0xa9, 0xd8, 0xe4, 0x75, 0xef, 0x11, 0xd9, 0x7a, 0x96, 0x25, 0x79, 0x6e, 0x54, 0x7c, 0x0a, 0x06,
	0x21, 0xa4, 0xdb, 0xe4, 0xbf, 0x40, 0x25, 0x31, 0x56, 0xdd, 0x5d, 0x77, 0xaf, 0xe2, 0xe7, 0x87,
	0x4c, 0x45, 0x85, 0xb2, 0x5b, 0x5d, 0xc9, 0x55, 0x7b, 0xf0, 0x8e, 0x08, 0x2d, 0xed, 0x8f, 0x55,
	0x1c, 0x46, 0x19, 0x9b, 0x0a, 0x72, 0x4d, 0x35, 0x0d, 0xf4, 0x07, 0x10, 0x36, 0x8a, 0x40, 0x91,
	0x8a, 0x0b, 0x1e, 0x9d, 0x96, 0x8e, 0xcb, 0x8a, 0xf7, 0x8e, 0x6c, 0x97, 0x98, 0xa7, 0xd1, 0x47,
	0x4c, 0xfa, 0xf0, 0x4a, 0x43, 0x40, 0x9f, 0x90, 0xb5, 0xd8, 0x86, 0xb2, 0xde, 0xcd, 0xfa, 0x6d,
	0xfe, 0x8f, 0x09, 0xf1, 0xb9, 0x46, 0xfc, 0xc2, 0xeb, 0x7d, 0x75, 0xc9, 0xf5, 0x3f, 0xf0, 0x28,
	0x31, 0x31, 0x4b, 0x27, 0xfd, 0xfb, 0x18, 0xe8, 0x19, 0x21, 0xc1, 0xb4, 0x7b, 0x53, 0xad, 0xec,
	0x56, 0xf6, 0x36, 0xeb, 0x62, 0xb1, 0xac, 0xe5, 0xd4, 0xfc, 0x19, 0x84, 0xf7, 0x7d, 0x85, 0x5c,
	0x9d, 0x8f, 0x4c, 0x4f, 0xc8, 0x06, 0x0e, 0x35, 0x34, 0xb2, 0x5d, 0x17, 0x03, 0xe1, 0x3c, 0xbf,
	0x15, 0x7c, 0xf6, 0x56, 0x70, 0xdd, 0x69, 0x65, 0x82, 0xe1, 0xd9, 0x97, 0x7c, 0x50, 0xe3, 0xaf,
	0x87, 0x1a, 0x5e, 0x02, 0x4a, 0x7f, 0x1d, 0x8b, 0x37, 0xfa, 0x82, 0xac, 0x67, 0xd5, 0x50, 0xa2,
	0xb4, 0xbd, 0x6c, 0xd6, 0xef, 0x2e, 0xc6, 0x3a, 0x6b, 0x9e, 0x43, 0x80, 0x39, 0x6d, 0x4a, 0xa0,
	0x47, 0x64, 0xd5, 0x68, 0x08, 0xaa, 0x15, 0x4b, 0xaa, 0x2d, 0xd6, 0xfa, 0xcc, 0xa6, 0x7d, 0x6b,
	0xa7, 0x27, 0x64, 0xcd, 0xd8, 0xc5, 0x54, 0x57, 0x2d, 0x68, 0x7f, 0x39, 0x90, 0xb5, 0xfa, 0x05,
	0xe2, 0xc1, 0xd6, 0xe7, 0xc3, 0x2b, 0xb7, 0xc8, 0xa9, 0xec, 0x81, 0xd1, 0x32, 0x80, 0xd0, 0x6b,
	0x93, 0x9b, 0x6f, 0x74, 0x28, 0x11, 0xe6, 0x8d, 0x3e, 0x7c, 0x48, 0xc0, 0x20, 0x3d, 0x26, 0xff,
	0xbf, 0xcf, 0x95, 0x62, 0xbc, 0x77, 0x96, 0xfa, 0xbf, 0x3f, 0x75, 0x1f, 0x3e, 0x1c, 0x8d, 0x99,
	0x73, 0x31, 0x66, 0xce, 0xe5, 0x98, 0xb9, 0x9f, 0x52, 0xe6, 0x7e, 0x4b, 0x99, 0x3b, 0x4a, 0x99,
	0xfb, 0x23, 0x65, 0xee, 0xcf, 0x94, 0x39, 0x97, 0x29, 0x73, 0xbf, 0x4c, 0x98, 0x33, 0x9a, 0x30,
	0xe7, 0x62, 0xc2, 0x9c, 0xb7, 0x1b, 0x25, 0xb6, 0xb9, 0x66, 0x1f, 0xfb, 0xbf, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x7a, 0x1f, 0x31, 0xd0, 0x3f, 0x04, 0x00, 0x00,
}

func (this *Int64JsonNested) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&kubeproto.Int64JsonNested{")
	s = append(s, "Count: "+fmt.Sprintf("%#v", this.Count)+",\n")
	s = append(s, "Total: "+fmt.Sprintf("%#v", this.Total)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Int64JsonCondition) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&kubeproto.Int64JsonCondition{")
	s = append(s, "ObservedGeneration: "+fmt.Sprintf("%#v", this.ObservedGeneration)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Int64JsonFixtureSpec) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&kubeproto.Int64JsonFixtureSpec{")
	if this.Nested != nil {
		s = append(s, "Nested: "+fmt.Sprintf("%#v", this.Nested)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Int64JsonFixtureStatus) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&kubeproto.Int64JsonFixtureStatus{")
	s = append(s, "ObservedGeneration: "+fmt.Sprintf("%#v", this.ObservedGeneration)+",\n")
	s = append(s, "Total: "+fmt.Sprintf("%#v", this.Total)+",\n")
	if this.Conditions != nil {
		s = append(s, "Conditions: "+fmt.Sprintf("%#v", this.Conditions)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *UpdateInt64JsonFixtureRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&kubeproto.UpdateInt64JsonFixtureRequest{")
	if this.Fixture != nil {
		s = append(s, "Fixture: "+fmt.Sprintf("%#v", this.Fixture)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringInt64JsonUt(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Int64JsonNested) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Int64JsonNested) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Int64JsonNested) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Total != 0 {
		i = encodeVarintInt64JsonUt(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x10
	}
	if m.Count != 0 {
		i = encodeVarintInt64JsonUt(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Int64JsonCondition) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Int64JsonCondition) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Int64JsonCondition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ObservedGeneration != 0 {
		i = encodeVarintInt64JsonUt(dAtA, i, uint64(m.ObservedGeneration))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Int64JsonFixtureSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Int64JsonFixtureSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Int64JsonFixtureSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Nested != nil {
		{
			size, err := m.Nested.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintInt64JsonUt(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Int64JsonFixtureStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Int64JsonFixtureStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Int64JsonFixtureStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Conditions) > 0 {
		for iNdEx := len(m.Conditions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Conditions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintInt64JsonUt(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Total != 0 {
		i = encodeVarintInt64JsonUt(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x10
	}
	if m.ObservedGeneration != 0 {
		i = encodeVarintInt64JsonUt(dAtA, i, uint64(m.ObservedGeneration))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Int64JsonFixture) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Int64JsonFixture) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UpdateInt64JsonFixtureRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateInt64JsonFixtureRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UpdateInt64JsonFixtureRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Fixture != nil {
		{
			size, err := m.Fixture.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintInt64JsonUt(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintInt64JsonUt(dAtA []byte, offset int, v uint64) int {
	offset -= sovInt64JsonUt(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Int64JsonNested) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Count != 0 {
		n += 1 + sovInt64JsonUt(uint64(m.Count))
	}
	if m.Total != 0 {
		n += 1 + sovInt64JsonUt(uint64(m.Total))
	}
	return n
}

func (m *Int64JsonCondition) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ObservedGeneration != 0 {
		n += 1 + sovInt64JsonUt(uint64(m.ObservedGeneration))
	}
	return n
}

func (m *Int64JsonFixtureSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Nested != nil {
		l = m.Nested.Size()
		n += 1 + l + sovInt64JsonUt(uint64(l))
	}
	return n
}

func (m *Int64JsonFixtureStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ObservedGeneration != 0 {
		n += 1 + sovInt64JsonUt(uint64(m.ObservedGeneration))
	}
	if m.Total != 0 {
		n += 1 + sovInt64JsonUt(uint64(m.Total))
	}
	if len(m.Conditions) > 0 {
		for _, e := range m.Conditions {
			l = e.Size()
			n += 1 + l + sovInt64JsonUt(uint64(l))
		}
	}
	return n
}

func (m *UpdateInt64JsonFixtureRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Fixture != nil {
		l = m.Fixture.Size()
		n += 1 + l + sovInt64JsonUt(uint64(l))
	}
	return n
}

func sovInt64JsonUt(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozInt64JsonUt(x uint64) (n int) {
	return sovInt64JsonUt(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Int64JsonNested) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Int64JsonNested{`,
		`Count:` + fmt.Sprintf("%v", this.Count) + `,`,
		`Total:` + fmt.Sprintf("%v", this.Total) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Int64JsonCondition) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Int64JsonCondition{`,
		`ObservedGeneration:` + fmt.Sprintf("%v", this.ObservedGeneration) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Int64JsonFixtureSpec) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Int64JsonFixtureSpec{`,
		`Nested:` + strings.Replace(this.Nested.String(), "Int64JsonNested", "Int64JsonNested", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Int64JsonFixtureStatus) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForConditions := "[]*Int64JsonCondition{"
	for _, f := range this.Conditions {
		repeatedStringForConditions += strings.Replace(f.String(), "Int64JsonCondition", "Int64JsonCondition", 1) + ","
	}
	repeatedStringForConditions += "}"
	s := strings.Join([]string{`&Int64JsonFixtureStatus{`,
		`ObservedGeneration:` + fmt.Sprintf("%v", this.ObservedGeneration) + `,`,
		`Total:` + fmt.Sprintf("%v", this.Total) + `,`,
		`Conditions:` + repeatedStringForConditions + `,`,
		`}`,
	}, "")
	return s
}
func (this *UpdateInt64JsonFixtureRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&UpdateInt64JsonFixtureRequest{`,
		`Fixture:` + strings.Replace(this.Fixture.String(), "Int64JsonFixture", "Int64JsonFixture", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringInt64JsonUt(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Int64JsonNested) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInt64JsonUt
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Int64JsonNested: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Int64JsonNested: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInt64JsonUt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInt64JsonUt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipInt64JsonUt(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInt64JsonUt
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Int64JsonCondition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInt64JsonUt
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Int64JsonCondition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Int64JsonCondition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObservedGeneration", wireType)
			}
			m.ObservedGeneration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInt64JsonUt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ObservedGeneration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipInt64JsonUt(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInt64JsonUt
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Int64JsonFixtureSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInt64JsonUt
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Int64JsonFixtureSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Int64JsonFixtureSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nested", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInt64JsonUt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInt64JsonUt
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInt64JsonUt
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Nested == nil {
				m.Nested = &Int64JsonNested{}
			}
			if err := m.Nested.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInt64JsonUt(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInt64JsonUt
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Int64JsonFixtureStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInt64JsonUt
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Int64JsonFixtureStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Int64JsonFixtureStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObservedGeneration", wireType)
			}
			m.ObservedGeneration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInt64JsonUt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ObservedGeneration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInt64JsonUt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Conditions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInt64JsonUt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInt64JsonUt
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInt64JsonUt
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Conditions = append(m.Conditions, &Int64JsonCondition{})
			if err := m.Conditions[len(m.Conditions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInt64JsonUt(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInt64JsonUt
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateInt64JsonFixtureRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInt64JsonUt
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateInt64JsonFixtureRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateInt64JsonFixtureRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fixture", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInt64JsonUt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInt64JsonUt
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInt64JsonUt
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Fixture == nil {
				m.Fixture = &Int64JsonFixture{}
			}
			if err := m.Fixture.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInt64JsonUt(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInt64JsonUt
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipInt64JsonUt(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowInt64JsonUt
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInt64JsonUt
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInt64JsonUt
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthInt64JsonUt
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupInt64JsonUt
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthInt64JsonUt
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthInt64JsonUt        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowInt64JsonUt          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupInt64JsonUt = fmt.Errorf("proto: unexpected end of group")
)

type Int64JsonFixture struct {
	metav1.TypeMeta   `protobuf:"bytes,1,opt,name=type_meta,json=typeMeta,proto3,embedded=type_meta" json:",inline"`
	metav1.ObjectMeta `protobuf:"bytes,2,opt,name=metadata,proto3,embedded=metadata" json:"metadata,omitempty"`
	// Spec of the desired behavior of the Int64JsonFixture.
	Spec Int64JsonFixtureSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// Most recently observed status of the Int64JsonFixture.
	Status Int64JsonFixtureStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *Int64JsonFixture) GetTypeMeta() *metav1.TypeMeta {
	return &m.TypeMeta
}

func (m *Int64JsonFixture) GetMetadata() *metav1.ObjectMeta {
	return &m.ObjectMeta
}

func (m *Int64JsonFixture) GetSpec() Int64JsonFixtureSpec {
	if m != nil {
		return m.Spec
	}
	return Int64JsonFixtureSpec{}
}

func (m *Int64JsonFixture) GetStatus() Int64JsonFixtureStatus {
	if m != nil {
		return m.Status
	}
	return Int64JsonFixtureStatus{}
}

func (m *Int64JsonFixture) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintInt64JsonUt(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintInt64JsonUt(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintInt64JsonUt(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.TypeMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintInt64JsonUt(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Int64JsonFixture) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TypeMeta.Size()
	n += 1 + l + sovInt64JsonUt(uint64(l))
	l = m.ObjectMeta.Size()
	n += 1 + l + sovInt64JsonUt(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovInt64JsonUt(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovInt64JsonUt(uint64(l))
	return n
}

func (this *Int64JsonFixture) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Int64JsonFixture{`,
		`TypeMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.TypeMeta), "TypeMeta", "metav1.TypeMeta", 1), `&`, ``, 1) + `,`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "metav1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "Int64JsonFixtureSpec", "Int64JsonFixtureSpec", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "Int64JsonFixtureStatus", "Int64JsonFixtureStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}

func (m *Int64JsonFixture) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInt64JsonUt
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Int64JsonFixture: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Int64JsonFixture: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TypeMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInt64JsonUt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInt64JsonUt
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInt64JsonUt
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TypeMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInt64JsonUt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInt64JsonUt
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInt64JsonUt
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInt64JsonUt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInt64JsonUt
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInt64JsonUt
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInt64JsonUt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInt64JsonUt
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInt64JsonUt
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInt64JsonUt(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthInt64JsonUt
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthInt64JsonUt
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

/* As gogo proto's jsonpb library does not support marshal and unmarshal for
   inline field (TypeMeta), we work around this by implementing the
   marshal and unmarshal functions for Spec and Status respectively. */
func (m *Int64JsonFixtureSpec) MarshalJSON() ([]byte,error) {
	var buf bytes.Buffer
	err := (&jsonpb.Marshaler{
	  EnumsAsInts: false,
	  EmitDefaults: false,
	  OrigName: false,
	  AnyResolver: &util.GenericResolver{},
	}).Marshal(&buf, m)
	return buf.Bytes(), err
}

func (m *Int64JsonFixtureSpec) UnmarshalJSON(b []byte) error {
	err := (&jsonpb.Unmarshaler{
	  AllowUnknownFields: getAllowUnknownFieldsEnvVar(),
	  AnyResolver: &util.GenericResolver{},
	}).Unmarshal(bytes.NewReader(b), m)
	if err == nil {
        return nil
	}

    if !(strings.Contains(err.Error(), "cannot unmarshal string into Go value of type map[string]json.RawMessage") ||
         strings.Contains(err.Error(), "cannot unmarshal number into Go value of type map[string]json.RawMessage")) {
        return err
    }

	visited := make(map[reflect.Type]bool)
    var paths []util.InlineFieldMapping
	util.RemoveInlineFields(reflect.TypeOf(m), "", visited, &paths)
	if len(paths) > 0 {
	    b, err = util.ApplyInlineFields(b, paths)
	}
    type Alias Int64JsonFixtureSpec
    aux := (*Alias)(m)

    return json.Unmarshal(b, aux)
}

func (m *Int64JsonFixtureStatus) MarshalJSON() ([]byte,error) {
	var buf bytes.Buffer
	err := (&jsonpb.Marshaler{
	  EnumsAsInts: false,
	  EmitDefaults: false,
	  OrigName: false,
	  AnyResolver: &util.GenericResolver{},
	}).Marshal(&buf, m)
	return buf.Bytes(), err
}

func (m *Int64JsonFixtureStatus) UnmarshalJSON(b []byte) error {
    err := (&jsonpb.Unmarshaler{
      AllowUnknownFields: getAllowUnknownFieldsEnvVar(),
      AnyResolver: &util.GenericResolver{},
    }).Unmarshal(bytes.NewReader(b), m)
    if err == nil {
        return nil
    }
    if !(strings.Contains(err.Error(), "cannot unmarshal string into Go value of type map[string]json.RawMessage") ||
         strings.Contains(err.Error(), "cannot unmarshal number into Go value of type map[string]json.RawMessage")) {
        return err
    }

    visited := make(map[reflect.Type]bool)
    var paths []util.InlineFieldMapping
    util.RemoveInlineFields(reflect.TypeOf(m), "", visited, &paths)
    if len(paths) > 0 {
        b, err = util.ApplyInlineFields(b, paths)
    }
    type Alias Int64JsonFixtureStatus
    aux := (*Alias)(m)

    return json.Unmarshal(b, aux)
}

func (m *Int64JsonFixture) UnmarshalJSONPB(_ *jsonpb.Unmarshaler, b []byte) error {
	// Proto3 canonical JSON encodes int64/uint64 as quoted strings;
	// unquote them before delegating to encoding/json.
	msgType := reflect.TypeOf(m)
	b, err := util.UnquoteInt64Fields(b, util.CollectInt64Fields(msgType))
	if err != nil {
		return err
	}
	// Apply inline field flattening (TypeMeta is tagged ",inline").
	visited := make(map[reflect.Type]bool)
	var inlinePaths []util.InlineFieldMapping
	util.RemoveInlineFields(msgType, "", visited, &inlinePaths)
	if len(inlinePaths) > 0 {
		b, err = util.ApplyInlineFields(b, inlinePaths)
		if err != nil {
			return err
		}
	}
	// Alias strips UnmarshalJSONPB from the method set so encoding/json
	// processes fields directly without re-entering this function.
	type Alias Int64JsonFixture
	return json.Unmarshal(b, (*Alias)(m))
}

func (in *Int64JsonFixture) DeepCopy() *Int64JsonFixture {
	if in == nil {
		return nil
	}
	out := new(Int64JsonFixture)
	in.DeepCopyInto(out)
	return out
}

func (in *Int64JsonFixture) DeepCopyObject() k8sruntime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *Int64JsonFixture) DeepCopyInto(out *Int64JsonFixture) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = *proto.Clone(&in.Spec).(*Int64JsonFixtureSpec)
	out.Status = *proto.Clone(&in.Status).(*Int64JsonFixtureStatus)
}

func init() {
	SchemeBuilder.Register(&Int64JsonFixture{})
}

func (m *Int64JsonFixture) GetIndexedKeyValuePairs() ([]storage.IndexedField){
	var indexedFields []storage.IndexedField
	return indexedFields
}


func init() {
	gvk := schema.GroupVersionKind{
		Group: "michelangelo.api",
		Version: "v2",
		Kind: "Int64JsonFixture",
	}
	IndexesPathToKeyMap[gvk] = make(map[string]string)

	// default index
	IndexesPathToKeyMap[gvk]["metadata.namespace"] = "namespace"
	IndexesPathToKeyMap[gvk]["metadata.name"] = "name"
}

func (m *Int64JsonFixture) IsImmutableKind() bool {

	return false
}

func init() {
	CrdObjects["Int64JsonFixture"] = &Int64JsonFixture{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "michelangelo.api/v2",
			Kind: "Int64JsonFixture",
		},
	}
}

func (m *Int64JsonFixture) HasBlobFields() bool {
	return false
}

func (m *Int64JsonFixture) ClearBlobFields() {
}

func (m *Int64JsonFixture) FillBlobFields(object k8sruntime.Object) {
	other := object.(*Int64JsonFixture)
	m.Spec = other.Spec
	m.Status = other.Status
}

func init() {
	YamlSchemas["Int64JsonFixture"] = `apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: int64jsonfixtures.michelangelo.api
spec:
  group: michelangelo.api
  names:
    kind: Int64JsonFixture
    listKind: Int64JsonFixtureList
    plural: int64jsonfixtures
    singular: int64jsonfixture
  scope: Namespaced
  versions:
  - name: v2
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              nested:
                properties:
                  count:
                    format: int64
                    pattern: ^[-]?\d{1,19}$
                    type: string
                  total:
                    format: int64
                    pattern: ^[-]?\d{1,19}$
                    type: string
                type: object
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    observedGeneration:
                      format: int64
                      pattern: ^[-]?\d{1,19}$
                      type: string
                  type: object
                type: array
              observedGeneration:
                format: int64
                pattern: ^[-]?\d{1,19}$
                type: string
              total:
                format: int64
                pattern: ^[-]?\d{1,19}$
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
`
}